# dhcpd.conf

option domain-name "rack-e.local";
option domain-name-servers 10.0.199.25;

default-lease-time 600;
max-lease-time 7200;

ddns-update-style none;

subnet 172.16.90.0 netmask 255.255.255.0 {
 range 172.16.90.0 172.16.90.10;
 option routers 172.16.90.1;
 option domain-name-servers 10.0.199.25;
 option domain-name "rack-e.local";
}

subnet 172.16.100.0 netmask 255.255.255.0 {
 range 172.16.100.0 172.16.100.10;
 option routers 172.16.100.1;
 option domain-name-servers 10.0.199.25;
 option domain-name "rack-e.local";
}