template(name="CiscoLogs" type="string"
string="/var/log/cisco/%msg:R,ERE,1,FIELD:([A-Za-z0-9_-]+):--end%/messages.log")

if ($fromhost-ip != "127.0.0.1") then {
    action(type="omfile" dynaFile="CiscoLogs" createDirs="on" FileCreateMode="0777" DirCreateMode="0777")
    stop
}
