# dhcpd.conf

option domain-name "rack-f.local";
option domain-name-servers 10.0.199.26;

default-lease-time 600;
max-lease-time 7200;

ddns-update-style none;

subnet 172.16.110.0 netmask 255.255.255.0 {
 range 172.16.110.0 172.16.110.10;
 option routers 172.16.110.1;
 option domain-name-servers 10.0.199.26;
 option domain-name "rack-f.local";
}

subnet 172.16.120.0 netmask 255.255.255.0 {
 range 172.16.120.0 172.16.120.10;
 option routers 172.16.120.1;
 option domain-name-servers 10.0.199.26;
 option domain-name "rack-f.local";
}