[routeurs]
RACK-C-R1-MTL ansible_host=10.0.0.22
RACK-C-R2-Ottawa ansible_host=10.0.0.26

[routeurs:vars]
ansible_user=admin
ansible_password=cisco1234
ansible_network_os=cisco.ios.ios
ansible_connection=network_cli
ansible_become=yes
ansible_become_method=enable
ansible_become_password=class