[routeurs]
RACK-E-R1-MTL ansible_host=10.0.0.38
RACK-E-R2-Ottawa ansible_host=10.0.0.42

[routeurs:vars]
ansible_user=user
ansible_password=cisco1234
ansible_network_os=cisco.ios.ios
ansible_connection=network_cli
ansible_become=yes
ansible_become_method=enable
ansible_become_password=class