[rackservers]
#servers ip add

[rack_a]
#rack_a server ip add
[rack_b]
#rack_b server ip add
[rack_c]
#rack_c server ip add
[rack_d]
#rack_d server ip add
[rack_e]
#rack_e server ip add
[rack_f]
#rack_f server ip add
