- name: Updating servers and installing services
  hosts: rackservers
  become: yes

  vars:
    ansible_become_pass: "" #admin password
  tasks:
   - name: Servers update
     shell: sudo apt update && sudo apt upgrade -y
   
   - name: Apache2 installation
     apt:
      name: apache2
      state: present

   - name: Dnsmasq installation
     apt: 
      name: dnsmasq
      state: present

   - name : Chaning the directory cisco permission 
     file:
      path: /home/cisco
      state: directory
      mode: '0755'

   - name : Creating the hostnames.txt file for dnsmasq
     file:
      path: /home/cisco/hostnames.txt
      state: touch
      mode: '0666'

   - name : Disable systemd-resolved service
     systemd:
      name: systemd-resolved
      state: stopped
      enabled: false
     become: yes

   - name : Dnsmasq enable service
     systemd:
      name: dnsmasq
      state: restarted
      enabled: true
     become: yes

   - name: Chrony installation
     apt: 
      name: chrony
      state: present
      
   - name: TFTP installation
     apt: 
      name: tftpd-hpa
      state: present

   - name: DHCP installation
     apt: 
      name: isc-dhcp-server
      state: present

   - name: Syslog installation
     apt: 
      name: rsyslog 
      state: present
      
- name: Config for server Rack-A
  hosts: rack_a
  become: yes
  vars:
    ansible_become_pass: "" #admin password
  tasks:
    - name : Get the html and css code for GitHub
      get_url:
        url: "{{ item.url }}"
        dest: /var/www/html/
      loop:
        - { url: "https://raw.githubusercontent.com/nadersip/Reseaux4/refs/heads/main/rack_a/index.html"}
        - { url: "https://raw.githubusercontent.com/nadersip/Reseaux4/refs/heads/main/rack_a/style.css"}
    - name : Get the dnsmasq config file
      get_url:
        url: "https://raw.githubusercontent.com/nadersip/Reseaux4/refs/heads/main/rack_a/dnsmasq-config"
        dest: /etc/dnsmasq.d/rack-a.local
    - name: Get hostnames.txt file
      get_url: 
        url: "https://raw.githubusercontent.com/nadersip/Reseaux4/refs/heads/main/rack_a/hostnames.txt"
        dest: /home/cisco/hostnames.txt
    - name : Restarting Dnsmasq service
      systemd:
        name: dnsmasq
        state: restarted
        enabled: true
      become: yes

- name: Config for server Rack-B
  hosts: rack_b
  become: yes
  vars:
    ansible_become_pass: "" #admin password
  tasks:
    - name : Get the html and css code for GitHub
      get_url:
        url: "{{ item.url }}"
        dest: /var/www/html/
      loop:
        - { url: "https://raw.githubusercontent.com/nadersip/Reseaux4/refs/heads/main/rack_b/index.html"}
        - { url: "https://raw.githubusercontent.com/nadersip/Reseaux4/refs/heads/main/rack_b/style.css"}
    - name : Get the dnsmasq config file
      get_url:
        url: "https://raw.githubusercontent.com/nadersip/Reseaux4/refs/heads/main/rack_b/dnsmasq-config"
        dest: /etc/dnsmasq.d/rack-B.local
    - name: Get hostnames.txt file
      get_url: 
        url: "https://raw.githubusercontent.com/nadersip/Reseaux4/refs/heads/main/rack_b/hostnames.txt"
        dest: /home/cisco/hostnames.txt
    - name : Restarting Dnsmasq service
      systemd:
        name: dnsmasq
        state: restarted
        enabled: true
      become: yes

- name: Config for server Rack-C
  hosts: rack_c
  become: yes
  vars:
    ansible_become_pass: "" #admin password
  tasks:
    - name : Get the html and css code for GitHub
      get_url:
        url: "{{ item.url }}"
        dest: /var/www/html/
      loop:
        - { url: "https://raw.githubusercontent.com/nadersip/Reseaux4/refs/heads/main/rack_c/index.html"}
        - { url: "https://raw.githubusercontent.com/nadersip/Reseaux4/refs/heads/main/rack_c/style.css"}
    - name : Get the dnsmasq config file
      get_url:
        url: "https://raw.githubusercontent.com/nadersip/Reseaux4/refs/heads/main/rack_c/dnsmasq-config"
        dest: /etc/dnsmasq.d/rack-c.local
    - name: Get hostnames.txt file
      get_url: 
        url: "https://raw.githubusercontent.com/nadersip/Reseaux4/refs/heads/main/rack_c/hostnames.txt"
        dest: /home/cisco/hostnames.txt
    - name : Restarting Dnsmasq service
      systemd:
        name: dnsmasq
        state: restarted
        enabled: true
      become: yes

- name: Config for server Rack-D
  hosts: rack_d
  become: yes
  vars:
    ansible_become_pass: "" #admin password
  tasks:
    - name : Get the html and css code for GitHub
      get_url:
        url: "{{ item.url }}"
        dest: /var/www/html/
      loop:
        - { url: "https://raw.githubusercontent.com/nadersip/Reseaux4/refs/heads/main/rack_d/index.html"}
        - { url: "https://raw.githubusercontent.com/nadersip/Reseaux4/refs/heads/main/rack_d/style.css"}
    - name : Get the dnsmasq config file
      get_url:
        url: "https://raw.githubusercontent.com/nadersip/Reseaux4/refs/heads/main/rack_d/dnsmasq-config"
        dest: /etc/dnsmasq.d/rack-d.local
    - name: Get hostnames.txt file
      get_url: 
        url: "https://raw.githubusercontent.com/nadersip/Reseaux4/refs/heads/main/rack_d/hostnames.txt"
        dest: /home/cisco/hostnames.txt
    - name : Restarting Dnsmasq service
      systemd:
        name: dnsmasq
        state: restarted
        enabled: true
      become: yes        

- name: Config for server Rack-E
  hosts: rack_e
  become: yes
  vars:
    ansible_become_pass: "" #admin password
  tasks:
    - name : Get the html and css code for GitHub
      get_url:
        url: "{{ item.url }}"
        dest: /var/www/html/
      loop:
        - { url: "https://raw.githubusercontent.com/nadersip/Reseaux4/refs/heads/main/rack_e/index.html"}
        - { url: "https://raw.githubusercontent.com/nadersip/Reseaux4/refs/heads/main/rack_e/style.css"}
    - name : Get the dnsmasq config file
      get_url:
        url: "https://raw.githubusercontent.com/nadersip/Reseaux4/refs/heads/main/rack_e/dnsmasq-config"
        dest: /etc/dnsmasq.d/rack-e.local
    - name: Get hostnames.txt file
      get_url: 
        url: "https://raw.githubusercontent.com/nadersip/Reseaux4/refs/heads/main/rack_e/hostnames.txt"
        dest: /home/cisco/hostnames.txt
    - name : Restarting Dnsmasq service
      systemd:
        name: dnsmasq
        state: restarted
        enabled: true
      become: yes

- name: Config for server Rack-F
  hosts: rack_f
  become: yes
  vars:
    ansible_become_pass: "" #admin password
  tasks:
    - name : Get the html and css code for GitHub
      get_url:
        url: "{{ item.url }}"
        dest: /var/www/html/
      loop:
        - { url: "https://raw.githubusercontent.com/nadersip/Reseaux4/refs/heads/main/rack_f/index.html"}
        - { url: "https://raw.githubusercontent.com/nadersip/Reseaux4/refs/heads/main/rack_f/style.css"}
    - name : Get the dnsmasq config file
      get_url:
        url: "https://raw.githubusercontent.com/nadersip/Reseaux4/refs/heads/main/rack_f/dnsmasq-config"
        dest: /etc/dnsmasq.d/rack-f.local
    - name: Get hostnames.txt file
      get_url: 
        url: "https://raw.githubusercontent.com/nadersip/Reseaux4/refs/heads/main/rack_f/hostnames.txt"
        dest: /home/cisco/hostnames.txt
    - name : Restarting Dnsmasq service
      systemd:
        name: dnsmasq
        state: restarted
        enabled: true
      become: yes