# dhcpd.conf

option domain-name "rack-d.local";
option domain-name-servers 10.0.199.24;

default-lease-time 600;
max-lease-time 7200;

ddns-update-style none;

subnet 172.16.70.0 netmask 255.255.255.0 {
 range 172.16.70.0 172.16.70.10;
 option routers 172.16.70.1;
 option domain-name-servers 10.0.199.24;
 option domain-name "rack-d.local";
}

subnet 172.16.80.0 netmask 255.255.255.0 {
 range 172.16.80.0 172.16.80.10;
 option routers 172.16.80.1;
 option domain-name-servers 10.0.199.24;
 option domain-name "rack-d.local";
}